name: Check for Changes_

on:
  push:
    branches:
      - main

jobs:
  veracode-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: pull dependencies
      run: | 
        mvn clean install 
    
    - name: package components for analysis
      run: |
        curl -fsS https://tools.veracode.com/veracode-cli/install | sh
        ./veracode package --source ./ --trust --output ./verascan --debug
        
    - name: debug
      run: |
        ls -la 
        ls -la ./verascan

    - name: upload components for analysis
      uses: veracode/veracode-uploadandscan-action@0.2.6
      with:
        appname: 'AEM'
        createprofile: true
        filepath: './verascan'
        vid: '${{ secrets.API_ID }}'
        vkey: '${{ secrets.API_KEY }}'
        exclude: '*test*'
